#!/bin/bash

docker run --name db-postgres-dev \
 --network bmt-rede-docker \
  -e POSTGRES_USER=postgres \
  -e POSTGRES_PASSWORD=sacadura10 \
  -e POSTGRES_DB=db-postgres-dev \
  -p 5432:5432 \
  -d postgres:16
